### ISSUE TITLE
Serializing Excel XML should treat empty environment value same as default

### ISSUE THREAD

**Issue by wachulski** [wachulski/merlin#16]
```
myParam:
  value:
    - Test: 15
    - default: 20
```

will put '' (empty) to cell representing Local environment, should be same as default (20). This is the consequence of a new semantics of missing environment values introduced with #11.
