### ISSUE TITLE
"default" is not translated into XML properly if it is not listed last in the YML

### ISSUE THREAD

**Issue by wachulski** [wachulski/merlin#18]
When listing values in config-params.yml, everything works fine if default comes last:
```
 __<administrateCustomerId>__:
    value:
    - __TemplateName__: __CustomerId__
    - A11: 210000
    - A14: 230000
    - AM7: 270000
    - AM8: 280000
    - BETA2: 14
    - Developer: 1
    - US8: 980000
    - Verification: 14
    - default: 240000
```

When default is not the last option, the specific values keep working, but the default value does not turn up in the web.config:
```
 __<administrateCustomerId>__:
    value:
    - __TemplateName__: __CustomerId__
    - A11: 210000
    - A14: 230000
    - AM7: 270000
    - AM8: 280000
    - BETA2: 14
    - Developer: 1
    - US8: 980000
    - default: 240000
    - Verification: 14
```

Wrong end result in web.config (this one is from AM3):
```
<!-- General customer settings -->
<add key="administrateCustomerId" value="" />  <!-- Which customer can add or edit customers -->
```
